export const tileTypes = [
  {
    id: "tile_grass",
    name: "Grass",
    color: "#006400",
    backgroundColor: "#90EE90",
    theme: "lemonade",
    resources: ["resource_grass_01"],
    rarity: 0.3,
  },
  {
    id: "tile_trees",
    name: "Trees",
    color: "#ffdfcb",
    backgroundColor: "#1f691f",
    theme: "forest",
    resources: ["item_stick_01", "resource_trees_01", "resource_trees_oak_02"],
    rarity: 0.3,
  },
  {
    id: "tile_rocky_outcrop",
    name: "Rocky Outcrop",
    color: "#F0F0F0",
    backgroundColor: "#696969",
    theme: "coffee",
    resources: ["resource_stones_01"],
    rarity: 0.3,
  },
  {
    id: "tile_campsite",
    name: "Campsite",
    color: "#FFD700",
    backgroundColor: "#8B4513",
    theme: "retro",
    resources: ["resource_campfire_01"],
    rarity: 0.02,
  },
  {
    id: "tile_derelict_workshop",
    name: "Derelict Workshop",
    color: "#F0E68C",
    backgroundColor: "#708090",
    theme: "nord",
    resources: [
      "resource_crafting_item_stone_axe_01",
      "resource_crafting_item_broom_01",
    ],
    rarity: 0.02,
  },
  {
    id: "tile_enchanted_grove",
    name: "Enchanted Grove",
    color: "#FFD700",
    backgroundColor: "#228B22",
    theme: "forest",
    resources: ["resource_enchanted_trees", "resource_fairy_flower"],
    rarity: 0.2,
  },
  {
    id: "tile_mystic_marsh",
    name: "Mystic Marsh",
    color: "#ADFF2F",
    backgroundColor: "#2F4F4F",
    theme: "swamp",
    resources: ["resource_mud", "resource_cattails"],
    rarity: 0.25,
  },
  {
    id: "tile_mountain_peak",
    name: "Mountain Peak",
    color: "#FFFFFF",
    backgroundColor: "#A9A9A9",
    theme: "mountain",
    resources: ["resource_mountain_rock", "resource_rare_mineral"],
    rarity: 0.15,
  },
  {
    id: "tile_frozen_wastes",
    name: "Frozen Wastes",
    color: "#191970",
    backgroundColor: "#E0FFFF",
    theme: "frozen",
    resources: ["resource_ice_crystal", "resource_frozen_rock"],
    rarity: 0.1,
  },
  {
    id: "tile_cavern_of_echoes",
    name: "Cavern of Echoes",
    color: "#DDA0DD",
    backgroundColor: "#2F4F4F",
    theme: "cave",
    resources: ["resource_ruby", "resource_cave_fungus"],
    rarity: 0.1,
  },
  {
    id: "tile_sunny_meadow",
    name: "Sunny Meadow",
    color: "#8B4513",
    backgroundColor: "#FFFF00",
    theme: "meadow",
    resources: ["resource_blooming_flower", "resource_fresh_grass"],
    rarity: 0.3,
  },
  {
    id: "tile_dense_thicket",
    name: "Dense Thicket",
    color: "#ADFF2F",
    backgroundColor: "#006400",
    theme: "forest",
    resources: ["resource_thicket_branches", "resource_nature_moss"],
    rarity: 0.25,
  },
  {
    id: "tile_crystal_cavern",
    name: "Crystal Cavern",
    color: "#FF69B4",
    backgroundColor: "#4B0082",
    theme: "cave",
    resources: ["resource_amethyst", "resource_crystal_gems"],
    rarity: 0.1,
  },
  {
    id: "tile_abandoned_mine",
    name: "Abandoned Mine",
    color: "#FFD700",
    backgroundColor: "#8B4513",
    theme: "mine",
    resources: ["resource_mine_ore", "resource_dust"],
    rarity: 0.2,
  },
  {
    id: "tile_wonderous_waterfall",
    name: "Wonderous Waterfall",
    color: "#FFFFFF",
    backgroundColor: "#4169E1",
    theme: "waterfall",
    resources: ["resource_spring_water", "resource_water_plants"],
    rarity: 0.2,
  },
  {
    id: "tile_marketplace",
    name: "Marketplace",
    color: "#FFD700",
    backgroundColor: "#800080",
    theme: "city",
    resources: [],
    rarity: 0.2,
  },
];
