import type { Item } from "./types.js";

export const items: Item[] = [
  {
    id: "item_spring_water",
    name: "Spring Water",
    description:
      "Clear, cold water from a spring by the beck, carried in a stoppered flask. Ada wants it for the pot, and Hobb for soaking flax.",
    type: "resource",
    rarity: "common",
    icon: "water-flask",
    stackable: true,
    maxStackSize: 10,
    equippable: false,
    value: 5,
    weight: 1,
  },
  {
    id: "item_seed_01",
    name: "Wild Seeds",
    description:
      "A pinch of hardy seeds shaken loose from meadow grass. Plant them in tilled soil to grow your own crops.",
    type: "resource",
    rarity: "common",
    icon: "plant-seed",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 2,
    weight: 0.1,
  },
  {
    id: "item_sickle_01",
    name: "Flint Sickle",
    description:
      "A curved flint blade lashed into a notched stick. Cuts wild flax and wheat, and one day a homestead's crops.",
    type: "tool",
    rarity: "common",
    icon: "sickle",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 40, max: 40 },
    value: 12,
    weight: 1.5,
  },
  {
    id: "item_fertilizer_01",
    name: "Ash Compost",
    description:
      "A crumbly mix of campfire ash and moss. Restores exhausted soil so it can be planted again.",
    type: "resource",
    rarity: "common",
    icon: "fertilizer-bag",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 4,
    weight: 0.5,
  },
  {
    id: "item_grass",
    name: "Wild Grass",
    description:
      "A handful of long meadow grass. Twisted tight, it makes a fair binding.",
    type: "resource",
    rarity: "common",
    icon: "high-grass",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 1,
    weight: 0.1,
  },
  {
    id: "item_flint",
    name: "Flint",
    description:
      "A grey nodule of flint from the beck bed. Knapped right it takes an edge sharper than most iron.",
    type: "resource",
    rarity: "common",
    icon: "flint-spark",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 2,
    weight: 0.3,
  },
  {
    id: "item_stick",
    name: "Stick",
    description:
      "A dry, straight length of fallen branch. Handles, hafts and kindling.",
    type: "resource",
    rarity: "common",
    icon: "wood-stick",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 1,
    weight: 0.3,
  },
  {
    id: "item_log",
    name: "Log",
    description:
      "A short length of seasoned wood cut from a fallen trunk. Heavy enough to make a club of.",
    type: "resource",
    rarity: "common",
    icon: "log",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 3,
    weight: 1,
  },
  {
    id: "item_stone",
    name: "Stone",
    description:
      "A squared stone prised out of an old field wall. Somebody cut it true, a long time ago.",
    type: "resource",
    rarity: "common",
    icon: "stone-pile",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 3,
    weight: 1,
  },
  {
    id: "item_flax",
    name: "Flax",
    description:
      "Stalks of wild flax, gone feral from fields nobody has sown in a hundred years.",
    type: "resource",
    rarity: "common",
    icon: "flax",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 2,
    weight: 0.2,
  },
  {
    id: "item_wild_wheat",
    name: "Wild Wheat",
    description:
      "Thin, hard ears of wheat run wild. Ada can make something of it.",
    type: "resource",
    rarity: "common",
    icon: "wheat",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 2,
    weight: 0.2,
  },
  {
    id: "item_yarrow",
    name: "Yarrow",
    description:
      "Feathery leaves and flat white flowers. Pressed on a cut, it stops the bleeding.",
    type: "resource",
    rarity: "common",
    icon: "herbs-bundle",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 2,
    weight: 0.1,
  },
  {
    id: "item_grass_twine",
    name: "Grass Twine",
    description:
      "Grass twisted into a tough cord. Hobb binds every tool head with it.",
    type: "resource",
    rarity: "common",
    icon: "rope-coil",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 2,
    weight: 0.1,
  },
  {
    id: "item_linen",
    name: "Linen",
    description:
      "Rough linen cloth from retted, beaten and spun wild flax. Stiff at first, softer with wear.",
    type: "resource",
    rarity: "common",
    icon: "rolled-cloth",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 6,
    weight: 0.3,
  },
  {
    id: "item_feather",
    name: "Feather",
    description:
      "A brown hen's feather. Stuffed between two layers of linen, they turn a knock.",
    type: "resource",
    rarity: "common",
    icon: "feather",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 1,
    weight: 0.05,
  },
  {
    id: "item_raw_chicken",
    name: "Raw Chicken",
    description: "A plucked feral hen. Stringy, but Ada will roast it.",
    type: "resource",
    rarity: "common",
    icon: "chicken-leg",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 3,
    weight: 0.5,
  },
  {
    id: "item_raw_rabbit",
    name: "Raw Rabbit",
    description: "A skinned rabbit, ready for the pot.",
    type: "resource",
    rarity: "common",
    icon: "rabbit",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 3,
    weight: 0.5,
  },
  {
    id: "item_rabbit_hide",
    name: "Rabbit Hide",
    description: "A small, soft pelt. Just big enough for a sling's pouch.",
    type: "resource",
    rarity: "common",
    icon: "rabbit-head",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 3,
    weight: 0.1,
  },
  {
    id: "item_adder_skin",
    name: "Adder Skin",
    description:
      "The zigzagged skin of an adder, thin and supple. Tough for its weight.",
    type: "resource",
    rarity: "common",
    icon: "snake",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 5,
    weight: 0.1,
  },
  {
    id: "item_flint_axe",
    name: "Flint Axe",
    description:
      "A knapped flint head bound to a stick with grass twine. It'll chop fallen wood, if not much else.",
    type: "tool",
    rarity: "common",
    icon: "stone-axe",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 40, max: 40 },
    value: 10,
    weight: 2,
  },
  {
    id: "item_flint_pick",
    name: "Flint Pick",
    description:
      "A heavy pointed flint lashed to a haft. Good for prising stones out of old walls.",
    type: "tool",
    rarity: "common",
    icon: "war-pick",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 40, max: 40 },
    value: 10,
    weight: 2.5,
  },
  {
    id: "item_wooden_club",
    name: "Wooden Club",
    description:
      "A length of log shaped into a club, with a knob at the end. Slow, but it lands hard.",
    type: "weapon",
    rarity: "common",
    icon: "wood-club",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 80, max: 80 },
    weapon: { style: "melee", damage: 14, speed: 2400 },
    value: 12,
    weight: 2,
  },
  {
    id: "item_sling",
    name: "Sling",
    description:
      "Two twine cords and a rabbit-hide pouch. Any pebble on the Landing will do for shot. Good against things that keep still, poor against anything that darts.",
    type: "weapon",
    rarity: "common",
    icon: "sling",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 80, max: 80 },
    weapon: { style: "ranged", damage: 10, speed: 2000 },
    value: 12,
    weight: 0.3,
  },
  {
    id: "item_linen_cap",
    name: "Linen Cap",
    description:
      "A padded linen cap tied under the chin. Keeps the sun off and softens a peck.",
    type: "armor",
    rarity: "common",
    icon: "phrygian-cap",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "head",
    defence: { melee: 5, ranged: 5, magic: 2 },
    value: 10,
    weight: 0.3,
  },
  {
    id: "item_linen_jerkin",
    name: "Quilted Linen Jerkin",
    description:
      "Two layers of linen quilted with hen feathers. Warm, light, and better than a bare shirt against teeth.",
    type: "armor",
    rarity: "common",
    icon: "sleeveless-jacket",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "chest",
    defence: { melee: 12, ranged: 10, magic: 3 },
    value: 20,
    weight: 1,
  },
  {
    id: "item_linen_leggings",
    name: "Linen Leggings",
    description:
      "Close-wound linen leggings, the sort drovers wear through gorse. An adder's fangs catch in the cloth.",
    type: "armor",
    rarity: "common",
    icon: "trousers",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "legs",
    defence: { melee: 8, ranged: 6, magic: 2 },
    value: 14,
    weight: 0.6,
  },
  {
    id: "item_adder_skin_gloves",
    name: "Adder-Skin Gloves",
    description:
      "Thin gloves stitched from adder skins. Hobb says wearing the snake is the best way not to be bitten by it.",
    type: "armor",
    rarity: "common",
    icon: "gloves",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "hands",
    defence: { melee: 6, ranged: 4, magic: 0 },
    value: 18,
    weight: 0.2,
  },
  {
    id: "item_blackberries",
    name: "Blackberries",
    description:
      "A handful of blackberries off the bramble. A mouthful of health.",
    type: "consumable",
    rarity: "common",
    icon: "raspberry",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    effects: [{ id: "effect_rest", strength: 4, duration: 0 }],
    value: 1,
    weight: 0.1,
  },
  {
    id: "item_yarrow_poultice",
    name: "Yarrow Poultice",
    description:
      "Yarrow boiled soft and wrapped in a wet pad. Press it on and the hurt eases.",
    type: "consumable",
    rarity: "common",
    icon: "bandage-roll",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    effects: [{ id: "effect_rest", strength: 20, duration: 0 }],
    value: 6,
    weight: 0.2,
  },
  {
    id: "item_roast_chicken",
    name: "Roast Chicken",
    description:
      "A feral hen roasted on a stick over Ada's fire. Filling, if you like chewing.",
    type: "consumable",
    rarity: "common",
    icon: "roast-chicken",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    effects: [{ id: "effect_rest", strength: 25, duration: 0 }],
    value: 8,
    weight: 0.5,
  },
  {
    id: "item_wheat_flatbread",
    name: "Wheat Flatbread",
    description: "Coarse flatbread baked on a hot stone. Keeps well in a pack.",
    type: "consumable",
    rarity: "common",
    icon: "bread",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    effects: [{ id: "effect_rest", strength: 12, duration: 0 }],
    value: 4,
    weight: 0.2,
  },
  {
    id: "item_rabbit_stew",
    name: "Rabbit Stew",
    description:
      "Rabbit simmered with yarrow in spring water. Eaten hot, it keeps you mending long after the bowl's empty.",
    type: "consumable",
    rarity: "common",
    icon: "camp-cooking-pot",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    effects: [
      { id: "effect_rest", strength: 10, duration: 0 },
      { id: "effect_rest", strength: 3, duration: 180 },
    ],
    value: 10,
    weight: 0.5,
  },
  {
    id: "item_foragers_brew",
    name: "Forager's Brew",
    description:
      "Blackberry and yarrow steeped in spring water. Ada swears it makes your hands quicker in the grass.",
    type: "consumable",
    rarity: "common",
    icon: "jug",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    effects: [{ id: "effect_bountiful", strength: 30, duration: 300 }],
    value: 8,
    weight: 0.3,
  },
  {
    id: "item_bakestone",
    name: "Bakestone",
    description:
      "A flat wall stone dressed smooth on one face. Set in the embers, it bakes flatbread. It goes back in your pack afterwards.",
    type: "tool",
    rarity: "common",
    icon: "stone-block",
    stackable: false,
    maxStackSize: 1,
    equippable: false,
    value: 8,
    weight: 2,
  },
  {
    id: "item_birch_log",
    name: "Birch Log",
    description:
      "A length of birch, white-barked and light. It burns hot, and the bark peels off in sheets.",
    type: "resource",
    rarity: "common",
    icon: "half-log",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 3,
    weight: 1,
  },
  {
    id: "item_birch_bark",
    name: "Birch Bark",
    description:
      "Papery white bark peeled from a birch log. Heated in a closed pot, it sweats a black tar.",
    type: "resource",
    rarity: "common",
    icon: "birch-trees",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 2,
    weight: 0.1,
  },
  {
    id: "item_birch_tar",
    name: "Birch Tar",
    description:
      "Black, sticky tar rendered from birch bark. It glues sinew to a bow, softens a salve, and a rag soaked in it burns for an hour.",
    type: "resource",
    rarity: "common",
    icon: "dripping-goo",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 5,
    weight: 0.2,
  },
  {
    id: "item_oak_log",
    name: "Oak Log",
    description:
      "Close-grained oak, heavy and hard. The best hafts, shafts and bow staves in the valley come out of it.",
    type: "resource",
    rarity: "common",
    icon: "wood-pile",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 5,
    weight: 1.5,
  },
  {
    id: "item_oak_bark",
    name: "Oak Bark",
    description:
      "Thick, ridged bark stripped from an old pollard oak. Soaked, it gives up the brown that turns hide to leather.",
    type: "resource",
    rarity: "common",
    icon: "oak-leaf",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 4,
    weight: 0.3,
  },
  {
    id: "item_bone",
    name: "Bone",
    description:
      "A clean, heavy leg bone. Split and ground, it makes a socket for a flint head or a handle for a knife.",
    type: "resource",
    rarity: "common",
    icon: "crossed-bones",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 3,
    weight: 0.3,
  },
  {
    id: "item_sinew",
    name: "Sinew",
    description:
      "Dried tendon pounded into threads. Stronger than any twine, and it shrinks tight as it dries.",
    type: "resource",
    rarity: "common",
    icon: "swirl-string",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 5,
    weight: 0.1,
  },
  {
    id: "item_salt",
    name: "Salt",
    description:
      "Grey rock salt, gritty and bitter. It cures meat and hides so they keep.",
    type: "resource",
    rarity: "common",
    icon: "powder",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 4,
    weight: 0.3,
  },
  {
    id: "item_wolf_pelt",
    name: "Wolf Pelt",
    description:
      "A grey wolf's pelt, still raw on the flesh side. Scrape and dry it at the lodge before it spoils.",
    type: "resource",
    rarity: "common",
    icon: "wolf-head",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 8,
    weight: 1,
  },
  {
    id: "item_boar_hide",
    name: "Boar Hide",
    description:
      "A thick, bristled boar hide. Too stiff to wear as it is. It wants salt and oak bark.",
    type: "resource",
    rarity: "common",
    icon: "boar",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 8,
    weight: 1.5,
  },
  {
    id: "item_cured_hide",
    name: "Cured Hide",
    description:
      "A wolf pelt scraped clean and dried on Jory's rack. Warm, and it turns a tooth.",
    type: "resource",
    rarity: "common",
    icon: "animal-hide",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 14,
    weight: 0.8,
  },
  {
    id: "item_bark_leather",
    name: "Bark-Tanned Leather",
    description:
      "Boar hide soaked in salt and oak bark until it went brown and supple. Rough work, but it's leather.",
    type: "resource",
    rarity: "common",
    icon: "animal-hide",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 18,
    weight: 0.8,
  },
  {
    id: "item_self_heal",
    name: "Self-Heal",
    description:
      "A low herb with purple flowers from the woodland clearings. Country people put it on every wound, hence the name.",
    type: "resource",
    rarity: "common",
    icon: "vine-flower",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 3,
    weight: 0.1,
  },
  {
    id: "item_raw_boar",
    name: "Boar Meat",
    description: "A haunch of wild boar, dark and heavy. Roast it or salt it.",
    type: "resource",
    rarity: "common",
    icon: "meat",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 5,
    weight: 1,
  },
  {
    id: "item_penny_buns",
    name: "Penny Buns",
    description:
      "Fat brown-capped mushrooms from under the oaks. Good eating, whatever Ada says. They grow in rings, not rows.",
    type: "consumable",
    rarity: "common",
    icon: "mushroom",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    effects: [{ id: "effect_rest", strength: 4, duration: 0 }],
    value: 2,
    weight: 0.2,
  },
  {
    id: "item_oak_and_bone_axe",
    name: "Oak-and-Bone Axe",
    description:
      "A flint blade seated in a bone socket and wedged into an oak haft. It bites the old pollard oaks, which would shatter a flint axe.",
    type: "tool",
    rarity: "common",
    icon: "wood-axe",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 80, max: 80 },
    value: 25,
    weight: 2.5,
  },
  {
    id: "item_oak_and_bone_pick",
    name: "Oak-and-Bone Pick",
    description:
      "A flint-tipped bone point set in an oak haft. Hard enough to dig rock salt out of a lick.",
    type: "tool",
    rarity: "common",
    icon: "war-pick",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 80, max: 80 },
    value: 25,
    weight: 2.5,
  },
  {
    id: "item_skinning_knife",
    name: "Skinning Knife",
    description:
      "A short flint blade in a bone handle, for skinning and scraping. Jory won't let a pelt on his rack that wasn't scraped with one.",
    type: "tool",
    rarity: "common",
    icon: "bone-knife",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 60, max: 60 },
    value: 15,
    weight: 0.4,
  },
  {
    id: "item_oak_spear",
    name: "Oak Spear",
    description:
      "An oak shaft with a knapped flint head bound on with twine. Quick in the hand, and the reach keeps beaks and teeth off you. It skids off a boar's shoulder.",
    type: "weapon",
    rarity: "common",
    icon: "stone-spear",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 120, max: 120 },
    weapon: { style: "melee", damage: 20, speed: 2200 },
    value: 25,
    weight: 2.5,
  },
  {
    id: "item_shortbow",
    name: "Sinew-Backed Shortbow",
    description:
      "An oak stave backed with sinew and birch tar. It drops a wolf before it closes, though a mob of crows on the wing is another matter.",
    type: "weapon",
    rarity: "common",
    icon: "pocket-bow",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 120, max: 120 },
    weapon: { style: "ranged", damage: 15, speed: 1800 },
    value: 30,
    weight: 1,
  },
  {
    id: "item_hide_hood",
    name: "Hide Hood",
    description:
      "A hood of cured wolf hide, fur side out. Warm, and it keeps teeth off your neck.",
    type: "armor",
    rarity: "common",
    icon: "hood",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "head",
    defence: { melee: 10, ranged: 8, magic: 3 },
    value: 20,
    weight: 0.5,
  },
  {
    id: "item_hide_jerkin",
    name: "Hide Jerkin",
    description:
      "Cured wolf hides stitched with sinew into a sleeveless jerkin. It turns a wolf's bite that would go straight through linen.",
    type: "armor",
    rarity: "common",
    icon: "leather-vest",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "chest",
    defence: { melee: 24, ranged: 20, magic: 5 },
    value: 40,
    weight: 2,
  },
  {
    id: "item_leather_leggings",
    name: "Bark-Leather Leggings",
    description:
      "Leggings of bark-tanned boar leather, stiff at the knee. A tusk has to work to get through them.",
    type: "armor",
    rarity: "common",
    icon: "armored-pants",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "legs",
    defence: { melee: 18, ranged: 14, magic: 4 },
    value: 30,
    weight: 1.2,
  },
  {
    id: "item_leather_boots",
    name: "Leather Boots",
    description:
      "Boar-leather boots with sinew-stitched soles. The first proper boots anyone's made in the valley.",
    type: "armor",
    rarity: "common",
    icon: "leather-boot",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "feet",
    defence: { melee: 10, ranged: 8, magic: 2 },
    value: 20,
    weight: 0.8,
  },
  {
    id: "item_pitch_torch",
    name: "Pitch Torch",
    description:
      "A stick with a linen rag bound round the head and soaked in birch tar. Carry it in your off hand to see in a cellar or any other hole in the ground.",
    type: "item",
    rarity: "common",
    icon: "primitive-torch",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "offHand",
    wornEffects: [{ id: "effect_light", strength: 50 }],
    value: 6,
    weight: 0.5,
  },
  {
    id: "item_spit_roast_boar",
    name: "Spit-Roast Boar",
    description:
      "A haunch of boar turned over Ada's fire until the fat runs. One of these and you can take a knock.",
    type: "consumable",
    rarity: "common",
    icon: "kebab-spit",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    effects: [{ id: "effect_rest", strength: 40, duration: 0 }],
    value: 12,
    weight: 0.8,
  },
  {
    id: "item_self_heal_salve",
    name: "Self-Heal Salve",
    description:
      "Self-Heal pounded into warm birch tar. It stings, then it doesn't, and the wound closes.",
    type: "consumable",
    rarity: "common",
    icon: "covered-jar",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    effects: [{ id: "effect_rest", strength: 35, duration: 0 }],
    value: 12,
    weight: 0.2,
  },
  {
    id: "item_salt_boar",
    name: "Salt Boar",
    description:
      "Strips of boar rubbed with salt and dried on Jory's rack. Keeps for a month in a pack.",
    type: "consumable",
    rarity: "common",
    icon: "ham-shank",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    effects: [{ id: "effect_rest", strength: 30, duration: 0 }],
    value: 12,
    weight: 0.3,
  },
  {
    id: "item_penny_bun_broth",
    name: "Penny Bun Broth",
    description:
      "Penny buns simmered with salt in spring water, the way Jory makes it. Ada won't touch it. It keeps you mending long after the bowl's empty.",
    type: "consumable",
    rarity: "common",
    icon: "bubbling-bowl",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    effects: [
      { id: "effect_rest", strength: 10, duration: 0 },
      { id: "effect_rest", strength: 4, duration: 300 },
    ],
    value: 10,
    weight: 0.5,
  },
  {
    id: "item_copper_ore",
    name: "Copper Ore",
    description:
      "Rock stained green and blue, heavy with copper. Three parts to one of tin, with charcoal under it, and it runs to bronze.",
    type: "resource",
    rarity: "common",
    icon: "ore",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 5,
    weight: 1,
  },
  {
    id: "item_tin_ore",
    name: "Tin Ore",
    description:
      "Dark, heavy grains of tinstone picked out of grey rock. A little goes a long way in a crucible of copper.",
    type: "resource",
    rarity: "common",
    icon: "minerals",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 8,
    weight: 1,
  },
  {
    id: "item_charcoal",
    name: "Charcoal",
    description:
      "Oak burnt slow under turf until it's black and light and rings when you drop it. It burns hotter than any log, hot enough to melt copper.",
    type: "resource",
    rarity: "common",
    icon: "coal-pile",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 3,
    weight: 0.3,
  },
  {
    id: "item_bronze_ingot",
    name: "Bronze Ingot",
    description:
      "A bar of fresh bronze, the colour of an old penny. It takes an edge and keeps it, and it doesn't care how hard the rock is.",
    type: "resource",
    rarity: "uncommon",
    icon: "metal-bar",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 20,
    weight: 1,
  },
  {
    id: "item_soapstone",
    name: "Soapstone",
    description:
      "Soft grey stone from the old quarry that you can carve with a knife and that won't crack in the heat. The Wardens cut a great deal of it, and nobody knows what for.",
    type: "resource",
    rarity: "common",
    icon: "rock",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 4,
    weight: 1,
  },
  {
    id: "item_yew_log",
    name: "Yew Log",
    description:
      "Red-hearted yew from a tree that grew out of a cliff crack. Tough and springy. It makes a hilt that won't split, and a bowyer would give a lot for a stave of it.",
    type: "resource",
    rarity: "common",
    icon: "wood-beam",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 8,
    weight: 1.5,
  },
  {
    id: "item_wardstone",
    name: "Wardstone",
    description:
      "A block of grey-green stone, fine as slate and heavier than it looks, that takes a cut line as clean as ink. The Wardens quarried their stones from this seam. Ansel Morrow will know it.",
    type: "resource",
    rarity: "uncommon",
    icon: "rune-stone",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 25,
    weight: 1.5,
  },
  {
    id: "item_crab_shell",
    name: "Crab Shell",
    description:
      "The back of a rock crab, grey and ridged like the scree it hides in. Blades and arrows skid off it. Riveted to a rim, it makes a buckler.",
    type: "resource",
    rarity: "common",
    icon: "crab-claw",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 10,
    weight: 1,
  },
  {
    id: "item_bat_wing",
    name: "Bat Wing",
    description:
      "A cave bat's wing, the skin thin enough to see a flame through. Scraped and oiled with tar, it makes a lantern pane.",
    type: "resource",
    rarity: "common",
    icon: "bat-wing",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 3,
    weight: 0.1,
  },
  {
    id: "item_stalker_hide",
    name: "Stalker Hide",
    description:
      "The pale, supple hide of a mine stalker, fine as glove leather and softer than anything that lives in daylight.",
    type: "resource",
    rarity: "common",
    icon: "lynx-head",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 12,
    weight: 0.5,
  },
  {
    id: "item_soapstone_mould",
    name: "Soapstone Mould",
    description:
      "Two halves of soapstone carved to the shape of a tool, a blade or a plate, and bound together to take molten bronze. It wears a little with every pour.",
    type: "tool",
    rarity: "common",
    icon: "sword-mold",
    stackable: false,
    maxStackSize: 1,
    equippable: false,
    durability: { current: 20, max: 20 },
    value: 12,
    weight: 2,
  },
  {
    id: "item_bronze_pick",
    name: "Bronze Pick",
    description:
      "A cast bronze pick on an oak haft. It cuts the rich seams and the grey-green stone in the lower galleries, which a bone pick only scratches.",
    type: "tool",
    rarity: "uncommon",
    icon: "mining",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 160, max: 160 },
    value: 50,
    weight: 3,
  },
  {
    id: "item_bronze_axe",
    name: "Bronze Axe",
    description:
      "A cast bronze axe head on an oak haft. It bites the old cliff yews, which turn flint and bone.",
    type: "tool",
    rarity: "uncommon",
    icon: "sharp-axe",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 160, max: 160 },
    value: 50,
    weight: 2.5,
  },
  {
    id: "item_bronze_sword",
    name: "Bronze Sword",
    description:
      "A leaf-shaped bronze blade with a yew hilt and a leather grip. It cuts a bat out of the air and reaches a stalker before it's back in the dark, but it rings off a rock crab's shell.",
    type: "weapon",
    rarity: "uncommon",
    icon: "broadsword",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 160, max: 160 },
    weapon: { style: "melee", damage: 26, speed: 2000 },
    value: 60,
    weight: 2.5,
  },
  {
    id: "item_bronze_helm",
    name: "Bronze Helm",
    description:
      "A cast bronze cap lined with cured hide. Heavy, and it rings when a stone hits it, which is better than the alternative.",
    type: "armor",
    rarity: "uncommon",
    icon: "crested-helmet",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "head",
    defence: { melee: 18, ranged: 14, magic: 2 },
    value: 45,
    weight: 2,
  },
  {
    id: "item_bronze_scale_coat",
    name: "Bronze Scale Coat",
    description:
      "Bronze scales sewn in rows onto a bark-leather coat. Teeth and falling rock skid off it. Anything that isn't a blade or a stone goes straight through.",
    type: "armor",
    rarity: "uncommon",
    icon: "scale-mail",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "chest",
    defence: { melee: 40, ranged: 30, magic: 4 },
    value: 90,
    weight: 5,
  },
  {
    id: "item_bronze_greaves",
    name: "Bronze Greaves",
    description:
      "Cast bronze shin plates strapped over hide. A crab's claw or a bat's teeth find nothing to grip.",
    type: "armor",
    rarity: "uncommon",
    icon: "greaves",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "legs",
    defence: { melee: 26, ranged: 20, magic: 3 },
    value: 60,
    weight: 3,
  },
  {
    id: "item_stalker_hide_gloves",
    name: "Stalker-Hide Gloves",
    description:
      "Gloves of pale stalker hide, stitched with sinew. Bett wears a pair at the forge, and they turn a thrown stone better than adder skin.",
    type: "armor",
    rarity: "uncommon",
    icon: "winter-gloves",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "hands",
    defence: { melee: 10, ranged: 12, magic: 3 },
    value: 30,
    weight: 0.3,
  },
  {
    id: "item_crab_shell_buckler",
    name: "Crab-Shell Buckler",
    description:
      "Two rock-crab shells riveted to a bronze rim, with a sinew grip. It turns a stone or a claw, but it takes the hand you'd hold a torch in.",
    type: "armor",
    rarity: "uncommon",
    icon: "round-shield",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "offHand",
    defence: { melee: 20, ranged: 30, magic: 0 },
    value: 45,
    weight: 2,
  },
  {
    id: "item_bat_wing_lantern",
    name: "Bat-Wing Lantern",
    description:
      "A little bronze lantern with panes of bat wing, scraped thin and oiled with tar, and a hook to hang it from your belt. It lights a gallery as well as a torch and leaves both hands free.",
    type: "item",
    rarity: "uncommon",
    icon: "old-lantern",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "accessory",
    wornEffects: [{ id: "effect_light", strength: 100 }],
    value: 40,
    weight: 1,
  },
  {
    id: "item_bog_moss",
    name: "Bog Moss",
    description:
      "Sphagnum pulled from the fen, green-gold and sopping. Wrung out and dried it holds its weight in water, and fine dust sticks to it and stays there.",
    type: "resource",
    rarity: "common",
    icon: "algae",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 3,
    weight: 0.1,
  },
  {
    id: "item_reeds",
    name: "Reeds",
    description:
      "Tall fen reeds cut green. They weave into traps and baskets, and their ash makes sand melt at a peat fire's heat.",
    type: "resource",
    rarity: "common",
    icon: "reed",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 2,
    weight: 0.2,
  },
  {
    id: "item_peat",
    name: "Peat",
    description:
      "A brick of cut peat, dark and fibrous. It burns slow and hot in the kiln, and the brown water it sits in tans a hide better than oak bark.",
    type: "resource",
    rarity: "common",
    icon: "brick-pile",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 3,
    weight: 0.6,
  },
  {
    id: "item_clay",
    name: "Clay",
    description:
      "Blue-grey clay dug from the bank, smooth and cold. Col Reeve says it throws as well as any downriver.",
    type: "resource",
    rarity: "common",
    icon: "clay-brick",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 3,
    weight: 0.8,
  },
  {
    id: "item_sand",
    name: "Lake Sand",
    description:
      "Pale sand from the mere's shore, fine and clean. Melted with reed ash it makes glass.",
    type: "resource",
    rarity: "common",
    icon: "beach-bucket",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 2,
    weight: 0.5,
  },
  {
    id: "item_raw_perch",
    name: "Perch",
    description:
      "A striped fen perch, cold from the water. Good grilled over peat, better in a broth.",
    type: "resource",
    rarity: "common",
    icon: "tropical-fish",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 4,
    weight: 0.4,
  },
  {
    id: "item_raw_pike",
    name: "Pike",
    description:
      "A long cut of pike, white and bony. Salted down in a crock it keeps for weeks.",
    type: "resource",
    rarity: "common",
    icon: "angler-fish",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 6,
    weight: 0.7,
  },
  {
    id: "item_fish_gut",
    name: "Fish Gut",
    description:
      "Pike gut, cleaned and scraped. Twisted and dried it makes a bowstring that won't stretch in the wet.",
    type: "resource",
    rarity: "common",
    icon: "bowels",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 4,
    weight: 0.1,
  },
  {
    id: "item_mossback_skin",
    name: "Mossback Skin",
    description:
      "The warty green skin of a mossback toad. It sheds water like a duck's back.",
    type: "resource",
    rarity: "common",
    icon: "frog",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 8,
    weight: 0.3,
  },
  {
    id: "item_pale_growth",
    name: "Pale Growth",
    description:
      "A fist of white growth cut from a colonised animal, fine threads laid in rows. It's cold, and it doesn't dry out. Ansel Morrow will want to see it.",
    type: "resource",
    rarity: "uncommon",
    icon: "mushrooms-cluster",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 30,
    weight: 0.2,
  },
  {
    id: "item_clay_jar",
    name: "Clay Jar",
    description:
      "A kiln-fired jar with a lid, stoppered with wax. The company's jars came up the river broken; these were made here.",
    type: "resource",
    rarity: "common",
    icon: "painted-pottery",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 6,
    weight: 0.6,
  },
  {
    id: "item_glass",
    name: "Glass",
    description:
      "A green, bubbled lump of fen glass. Nobody else in the valley can make it, and Col Reeve is prouder of it than he lets on.",
    type: "resource",
    rarity: "uncommon",
    icon: "glass-ball",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 20,
    weight: 0.4,
  },
  {
    id: "item_gut_string",
    name: "Gut Bowstring",
    description:
      "Three strands of pike gut twisted into a bowstring and dried on the rack. It pulls harder than sinew and holds in the wet.",
    type: "resource",
    rarity: "uncommon",
    icon: "bow-string",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 14,
    weight: 0.1,
  },
  {
    id: "item_fen_leather",
    name: "Peat-Tanned Leather",
    description:
      "Wolf hide steeped for days in peat water until it went dark and close-grained. Tougher than bark leather, and it doesn't take the wet.",
    type: "resource",
    rarity: "uncommon",
    icon: "animal-hide",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 28,
    weight: 0.7,
  },
  {
    id: "item_turf_spade",
    name: "Oak Turf Spade",
    description:
      "A long oak blade shod with bone, for cutting peat and digging clay out of the bank.",
    type: "tool",
    rarity: "common",
    icon: "spade",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 80, max: 80 },
    value: 15,
    weight: 2,
  },
  {
    id: "item_withy_fish_trap",
    name: "Withy Fish Trap",
    description:
      "A cone of woven reeds bound with twine, set in the reed margins where the perch run.",
    type: "tool",
    rarity: "common",
    icon: "basket",
    stackable: false,
    maxStackSize: 1,
    equippable: false,
    durability: { current: 40, max: 40 },
    value: 12,
    weight: 1.5,
  },
  {
    id: "item_floated_net",
    name: "Glass-Floated Net",
    description:
      "A linen net with a line of green glass floats along its head. Cast over open water it comes up heavy.",
    type: "tool",
    rarity: "uncommon",
    icon: "fishing-net",
    stackable: false,
    maxStackSize: 1,
    equippable: false,
    durability: { current: 60, max: 60 },
    value: 45,
    weight: 2,
  },
  {
    id: "item_yew_longbow",
    name: "Yew Longbow",
    description:
      "A tall stave of Scarp yew with a peat-leather grip and a gut string from the Sinks. It throws an arrow through a pike's back before it sees you, but a heron's pale plumage turns it like a wall.",
    type: "weapon",
    rarity: "uncommon",
    icon: "bow-arrow",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 160, max: 160 },
    weapon: { style: "ranged", damage: 24, speed: 2000 },
    value: 60,
    weight: 1.4,
  },
  {
    id: "item_mossback_waders",
    name: "Mossback Waders",
    description:
      "Chest-high waders of peat-tanned leather patched with mossback skin and sealed with birch tar. The cold still gets in, but slower. They're no greaves in a fight.",
    type: "armor",
    rarity: "uncommon",
    icon: "rubber-boot",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "legs",
    defence: { melee: 14, ranged: 12, magic: 3 },
    wornEffects: [{ id: "effect_cold_ward", strength: 100 }],
    value: 45,
    weight: 2,
  },
  {
    id: "item_spore_wrap",
    name: "Moss Spore-Wrap",
    description:
      "A linen wrap packed with dried bog moss, tied over nose and mouth. It catches some of what's in the air. It won't stop a blow.",
    type: "armor",
    rarity: "common",
    icon: "ninja-mask",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "head",
    defence: { melee: 3, ranged: 3, magic: 4 },
    wornEffects: [{ id: "effect_spore_ward", strength: 40 }],
    value: 25,
    weight: 0.3,
  },
  {
    id: "item_grilled_perch",
    name: "Grilled Perch",
    description:
      "A perch split and grilled over peat. It tastes of smoke and fen.",
    type: "consumable",
    rarity: "common",
    icon: "fish-cooked",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    effects: [{ id: "effect_rest", strength: 18, duration: 0 }],
    value: 6,
    weight: 0.4,
  },
  {
    id: "item_potted_pike",
    name: "Potted Pike",
    description:
      "Salted pike packed in a clay jar under a skin of fat. A settler's standby for a long day out.",
    type: "consumable",
    rarity: "common",
    icon: "mason-jar",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    effects: [{ id: "effect_rest", strength: 30, duration: 0 }],
    value: 12,
    weight: 0.6,
  },
  {
    id: "item_fen_broth",
    name: "Fen Broth",
    description:
      "Perch simmered in a jar in the kiln's embers, drunk scalding. It warms you to the fingers, and the warmth lasts a while in cold water.",
    type: "consumable",
    rarity: "common",
    icon: "cauldron",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    effects: [
      { id: "effect_rest", strength: 8, duration: 0 },
      { id: "effect_cold_ward", strength: 60, duration: 300 },
    ],
    value: 10,
    weight: 0.6,
  },
  {
    id: "item_wardens_stylus",
    name: "Warden's Stylus",
    description:
      "A bronze point set in a worn bone handle, the tip ground to a chisel edge. Ansel Morrow's own, from when he was sworn. It cuts warding lines at the table at camp's edge.",
    type: "tool",
    rarity: "rare",
    icon: "chisel",
    stackable: false,
    maxStackSize: 1,
    equippable: false,
    value: 80,
    weight: 0.2,
  },
  {
    id: "item_inscribed_shard",
    name: "Inscribed Wardstone Shard",
    description:
      "A shard of wardstone cut all round with warding lines, closed about a scrap of pale growth. The stone is cold in the hand and seems to lean away from the fen.",
    type: "resource",
    rarity: "rare",
    icon: "broken-tablet",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 60,
    weight: 0.8,
  },
  {
    id: "item_warding_staff",
    name: "Warding Staff",
    description:
      "A yew staff shod in bronze and capped with an inscribed wardstone shard, bound on with gut. It doesn't cut. What it strikes is held and pressed, and a rock crab's shell is no help against that.",
    type: "weapon",
    rarity: "rare",
    icon: "wizard-staff",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 160, max: 160 },
    weapon: { style: "magic", damage: 22, speed: 2200 },
    value: 120,
    weight: 1.8,
  },
  {
    id: "item_iron_ore",
    name: "Iron Ore",
    description:
      "Rust-red ore from the unsealed level under Bett Oakes' mine, below where the Wardens stopped cutting. A bronze pick only just bites it, and it takes a bloomery's heat and a great deal of charcoal to smelt.",
    type: "resource",
    rarity: "common",
    icon: "gold-nuggets",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 10,
    weight: 1,
  },
  {
    id: "item_iron_ingot",
    name: "Iron Ingot",
    description:
      "A bloom of iron hammered and folded until the slag is out of it. Harder than bronze and slower to make, and it holds an edge.",
    type: "resource",
    rarity: "uncommon",
    icon: "gold-bar",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 40,
    weight: 1,
  },
  {
    id: "item_warden_steel",
    name: "Warden Steel",
    description:
      "Old steel prised out of a Warden's house on the line: a blade blank, hinges, a coil of mail gone brown but sound underneath. Nobody downriver makes steel this good any more.",
    type: "resource",
    rarity: "rare",
    icon: "metal-plate",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 60,
    weight: 1,
  },
  {
    id: "item_wool",
    name: "Feral Wool",
    description:
      "Coarse, greasy wool torn off on the thorns by sheep that have been wild for a hundred and twenty years. Full of burrs, and warm.",
    type: "resource",
    rarity: "common",
    icon: "wool",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 3,
    weight: 0.2,
  },
  {
    id: "item_beeswax",
    name: "Beeswax",
    description:
      "Dark wax from a wild hive in a steading wall. The holdfast waxes its masks with it and seals its jars.",
    type: "resource",
    rarity: "common",
    icon: "honeycomb",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 6,
    weight: 0.2,
  },
  {
    id: "item_mugwort",
    name: "Mugwort",
    description:
      "A grey-leaved hedge herb with a bitter smell. The descendants burn it on the walls, pack their masks with it and steep it, and swear the spores settle less where it's been.",
    type: "resource",
    rarity: "common",
    icon: "curled-leaf",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 3,
    weight: 0.1,
  },
  {
    id: "item_comfrey",
    name: "Comfrey",
    description:
      "Knitbone, run wild from the old kitchen gardens. The leaves go into salves for bruises, bites and breaks.",
    type: "resource",
    rarity: "common",
    icon: "linden-leaf",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 3,
    weight: 0.1,
  },
  {
    id: "item_wool_felt",
    name: "Wool Felt",
    description:
      "Feral wool fulled into a thick, close felt at the holdfast's loom. It keeps out the wind, the wet and most of what's in the air.",
    type: "resource",
    rarity: "common",
    icon: "rolled-cloth",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 10,
    weight: 0.3,
  },
  {
    id: "item_hound_pelt",
    name: "Hound Pelt",
    description:
      "The rough hide of a feral hound, bred down from the valley's old farm dogs. Tough enough to back mail with.",
    type: "resource",
    rarity: "common",
    icon: "hound",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 8,
    weight: 0.6,
  },
  {
    id: "item_grey_threads",
    name: "Grey Threads",
    description:
      "A hank of fine grey threads from a fallen host. They're dry, nearly weightless and faintly warm, unlike anything cut from an animal. A healer would want to study them; a warder would cut a line around them.",
    type: "resource",
    rarity: "uncommon",
    icon: "sewing-string",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 35,
    weight: 0.1,
  },
  {
    id: "item_honey",
    name: "Wild Honey",
    description:
      "Honey from the old steadings' hives, gone wild in the walls. Sweet, good for a cough, and the holdfast puts it in everything.",
    type: "consumable",
    rarity: "common",
    icon: "honey-jar",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    effects: [{ id: "effect_rest", strength: 8, duration: 0 }],
    value: 6,
    weight: 0.3,
  },
  {
    id: "item_spore_tincture",
    name: "Spore Tincture",
    description:
      "A stoppered jar of steeped mugwort and honey, bitter as bark. Drink it before you go out and your chest stays clear for a while. It thins the spores; it doesn't stop them.",
    type: "consumable",
    rarity: "uncommon",
    icon: "vial",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    effects: [{ id: "effect_spore_ward", strength: 80, duration: 300 }],
    value: 18,
    weight: 0.3,
  },
  {
    id: "item_comfrey_salve",
    name: "Comfrey Salve",
    description:
      "Comfrey pounded into beeswax and rubbed into bruises and bites. It knits you up faster than anything made at camp.",
    type: "consumable",
    rarity: "common",
    icon: "covered-jar",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    effects: [{ id: "effect_rest", strength: 45, duration: 0 }],
    value: 14,
    weight: 0.3,
  },
  {
    id: "item_iron_pick",
    name: "Iron Pick",
    description:
      "An iron pick on an oak haft. It bites where bronze skids, and it prises open what the Wardens bolted shut.",
    type: "tool",
    rarity: "uncommon",
    icon: "mining",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 240, max: 240 },
    value: 70,
    weight: 2.5,
  },
  {
    id: "item_iron_sword",
    name: "Iron Sword",
    description:
      "A plain forged sword, heavier than bronze and much harder. It cuts through a hound pack's scrabble of teeth before they can get round you.",
    type: "weapon",
    rarity: "uncommon",
    icon: "pointy-sword",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 240, max: 240 },
    weapon: { style: "melee", damage: 32, speed: 2000 },
    value: 80,
    weight: 3,
  },
  {
    id: "item_warden_blade",
    name: "Warden Steel Blade",
    description:
      "A Warden's blade blank finished at Bett's anvil: light, quick and still etched with closed lines along the fuller. It holds its edge in a host's thick hide better than iron.",
    type: "weapon",
    rarity: "rare",
    icon: "rune-sword",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 320, max: 320 },
    weapon: { style: "melee", damage: 36, speed: 1800 },
    value: 150,
    weight: 2.5,
  },
  {
    id: "item_crossbow",
    name: "Iron Crossbow",
    description:
      "A yew stock with an iron bow and a gut string, spanned with a lever. Slow to load, but a bolt goes through a mossback wolf's mat of moss where an arrow sticks in it.",
    type: "weapon",
    rarity: "uncommon",
    icon: "crossbow",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 240, max: 240 },
    weapon: { style: "ranged", damage: 44, speed: 2600 },
    value: 90,
    weight: 3.5,
  },
  {
    id: "item_wardstone_focus",
    name: "Wardstone Focus",
    description:
      "A hand-sized wardstone cut closed around a host's grey threads and set in Warden steel. It knows the network's shape, so it presses on a host like a hand on a door where a blade has to hack.",
    type: "weapon",
    rarity: "rare",
    icon: "floating-crystal",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 240, max: 240 },
    weapon: { style: "magic", damage: 32, speed: 2200 },
    value: 180,
    weight: 1.5,
  },
  {
    id: "item_iron_mail",
    name: "Iron Mail Shirt",
    description:
      "A shirt of riveted iron rings over a hound-hide lining. Heavier than bronze scale and better against everything, and it takes a little of the sting out of what isn't a blade.",
    type: "armor",
    rarity: "uncommon",
    icon: "mail-shirt",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "chest",
    defence: { melee: 56, ranged: 44, magic: 14 },
    value: 110,
    weight: 8,
  },
  {
    id: "item_iron_chausses",
    name: "Iron Mail Chausses",
    description: "Iron mail leggings, laced at the knee over hound hide.",
    type: "armor",
    rarity: "uncommon",
    icon: "leg-armor",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "legs",
    defence: { melee: 34, ranged: 28, magic: 10 },
    value: 80,
    weight: 5,
  },
  {
    id: "item_warden_mail",
    name: "Warden Mail",
    description:
      "A Warden's mail shirt, cleaned and relined with holdfast felt. Every ring is cut with a tiny closed line, and whatever those lines hold off, it isn't only steel.",
    type: "armor",
    rarity: "rare",
    icon: "chain-mail",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "chest",
    defence: { melee: 62, ranged: 50, magic: 32 },
    value: 200,
    weight: 6,
  },
  {
    id: "item_warden_gauntlets",
    name: "Warden Gauntlets",
    description:
      "Plates of Warden steel riveted to a hound-hide glove, lined on the knuckles like the stones.",
    type: "armor",
    rarity: "rare",
    icon: "gauntlet",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "hands",
    defence: { melee: 16, ranged: 16, magic: 12 },
    value: 70,
    weight: 1,
  },
  {
    id: "item_waxed_mask",
    name: "Waxed Mask",
    description:
      "A close felt mask packed with mugwort and waxed until it's stiff, the way the holdfast makes them. It filters far better than a moss wrap. Nothing filters all of it.",
    type: "armor",
    rarity: "uncommon",
    icon: "bird-mask",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "head",
    defence: { melee: 6, ranged: 5, magic: 8 },
    wornEffects: [{ id: "effect_spore_ward", strength: 100 }],
    value: 60,
    weight: 0.5,
  },
  {
    id: "item_spore_resin",
    name: "Spore Resin",
    description:
      "Amber sap from a colonised birch, tapped where the white threads run under the bark. It sets hard and clear, and a potter can fuse it into glass.",
    type: "resource",
    rarity: "uncommon",
    icon: "chemical-drop",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 20,
    weight: 0.3,
  },
  {
    id: "item_mycelium_mat",
    name: "Mycelium Mat",
    description:
      "A sheet of white root-felt peeled off a grown-through log, tough as wet leather and faintly warm. Salted and tanned, it makes a leather that shrugs off spores.",
    type: "resource",
    rarity: "uncommon",
    icon: "mushroom-gills",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 15,
    weight: 0.3,
  },
  {
    id: "item_chitin",
    name: "Fungal Chitin",
    description:
      "Plates of fungal crust gone hard as horn, broken off stones and stumps in the Bloom. It holds an edge better than bronze and weighs next to nothing.",
    type: "resource",
    rarity: "uncommon",
    icon: "beetle-shell",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 25,
    weight: 0.3,
  },
  {
    id: "item_threaded_heartwood",
    name: "Threaded Heartwood",
    description:
      "Oak heartwood from a tree the network has grown through, grey threads running with the grain like veins. It bends and comes back, and it doesn't split.",
    type: "resource",
    rarity: "rare",
    icon: "tree-roots",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 40,
    weight: 1,
  },
  {
    id: "item_threaded_spine",
    name: "Threaded Spine",
    description:
      "The backbone of a colonised elk, fused into one springy rod by the threads that grew through it. A bowyer would know what to do with it.",
    type: "resource",
    rarity: "rare",
    icon: "backbone-shell",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 45,
    weight: 1,
  },
  {
    id: "item_elk_hide",
    name: "Elk Hide",
    description:
      "A heavy hide off a colonised elk, patched with plates of chitin that grew into the skin. Good for lining armour.",
    type: "resource",
    rarity: "uncommon",
    icon: "deer-head",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 20,
    weight: 1,
  },
  {
    id: "item_moth_down",
    name: "Moth Down",
    description:
      "Soft pale down combed from a spore-moth swarm's wings, dusty with spores. Quilted into leather, it turns spore-bursts like wool turns rain.",
    type: "resource",
    rarity: "uncommon",
    icon: "fluffy-wing",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 15,
    weight: 0.1,
  },
  {
    id: "item_spore_glass",
    name: "Spore-Glass",
    description:
      "Fen glass fused with spore resin into a clear amber pane that fogs over in bad air instead of cracking. The Wardens' respirators had eyes of it.",
    type: "resource",
    rarity: "rare",
    icon: "crystal-cluster",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 45,
    weight: 0.5,
  },
  {
    id: "item_mycelium_leather",
    name: "Mycelium Leather",
    description:
      "Mycelium mats salted and tanned at the rack into a pale, supple leather. It's lighter than hide and spores don't settle on it.",
    type: "resource",
    rarity: "uncommon",
    icon: "animal-hide",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 40,
    weight: 0.5,
  },
  {
    id: "item_iron_axe",
    name: "Iron Axe",
    description:
      "An iron axe on an oak haft. It bites into grown-through wood that turns a bronze edge, and taps the weeping birches of the Bloom.",
    type: "tool",
    rarity: "uncommon",
    icon: "battered-axe",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 240, max: 240 },
    value: 70,
    weight: 2.5,
  },
  {
    id: "item_chitin_axe",
    name: "Chitin-Edged Axe",
    description:
      "An iron axe head with a cutting edge of fungal chitin set into it. It goes through a threaded oak the way an iron axe goes through a birch.",
    type: "tool",
    rarity: "uncommon",
    icon: "war-axe",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 300, max: 300 },
    value: 110,
    weight: 2,
  },
  {
    id: "item_chitin_pick",
    name: "Chitin-Edged Pick",
    description:
      "An iron pick tipped with chitin. It breaks the thick crusted boulders of the Bloom that an iron point only scratches.",
    type: "tool",
    rarity: "uncommon",
    icon: "war-pick",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 300, max: 300 },
    value: 110,
    weight: 2,
  },
  {
    id: "item_chitin_blade",
    name: "Chitin Blade",
    description:
      "A long blade of chitin plates riveted along an iron spine, with a threaded-heartwood hilt. It's light and wicked-sharp, and it bites into a host's grown-over hide where iron skids.",
    type: "weapon",
    rarity: "rare",
    icon: "crescent-blade",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 300, max: 300 },
    weapon: { style: "melee", damage: 44, speed: 1800 },
    value: 220,
    weight: 2,
  },
  {
    id: "item_spine_bow",
    name: "Spine-Bow",
    description:
      "A colonised elk's threaded spine backed onto a stave of threaded heartwood and strung with doubled gut. It draws light and throws hard, and it drops an elk or a moth swarm before they reach you.",
    type: "weapon",
    rarity: "rare",
    icon: "lightning-bow",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 300, max: 300 },
    weapon: { style: "ranged", damage: 40, speed: 2000 },
    value: 220,
    weight: 1.5,
  },
  {
    id: "item_filter_respirator",
    name: "Filter Respirator",
    description:
      "A felt hood with two spore-glass eyes and a sealed filter of mycelium mat and wax over the mouth, built to the pattern in Tam's grandmother's book. It keeps out more than any mask, and takes the edge off a spore-burst. Not all of it.",
    type: "armor",
    rarity: "rare",
    icon: "gas-mask",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "head",
    defence: { melee: 10, ranged: 8, magic: 22 },
    wornEffects: [{ id: "effect_spore_ward", strength: 160 }],
    value: 160,
    weight: 1,
  },
  {
    id: "item_chitin_cuirass",
    name: "Chitin Cuirass",
    description:
      "Overlapping chitin plates riveted onto elk hide over an iron frame. Lighter than mail and harder, and the spore-bursts that go through iron rings slide off it.",
    type: "armor",
    rarity: "rare",
    icon: "breastplate",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "chest",
    defence: { melee: 78, ranged: 70, magic: 46 },
    value: 240,
    weight: 6,
  },
  {
    id: "item_chitin_greaves",
    name: "Chitin Greaves",
    description:
      "Chitin plates laced over elk hide to the knee. They turn an elk's kick and a host's swing alike.",
    type: "armor",
    rarity: "rare",
    icon: "armor-cuisses",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "legs",
    defence: { melee: 50, ranged: 44, magic: 30 },
    value: 170,
    weight: 4,
  },
  {
    id: "item_mycelium_jerkin",
    name: "Mycelium Jerkin",
    description:
      "A jerkin of mycelium leather quilted with moth down. It stops less steel than chitin, but spore-bursts die in it.",
    type: "armor",
    rarity: "rare",
    icon: "armor-vest",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "chest",
    defence: { melee: 50, ranged: 44, magic: 60 },
    value: 180,
    weight: 2.5,
  },
  {
    id: "item_mycelium_boots",
    name: "Mycelium Boots",
    description:
      "Boots of mycelium leather soled with elk hide. The spores that coat the Bloom's floor don't cling to them.",
    type: "armor",
    rarity: "rare",
    icon: "fur-boot",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "feet",
    defence: { melee: 16, ranged: 14, magic: 16 },
    value: 80,
    weight: 1,
  },
  {
    id: "item_mycelium_gloves",
    name: "Mycelium Gloves",
    description:
      "Close gloves of mycelium leather lined with moth down, for handling what grows in the Bloom.",
    type: "armor",
    rarity: "rare",
    icon: "cooking-glove",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "hands",
    defence: { melee: 16, ranged: 14, magic: 16 },
    value: 80,
    weight: 0.5,
  },
  {
    id: "item_chitin_dibber",
    name: "Chitin Dibber",
    description:
      "A planting dibber of horn-hard chitin, grown rather than carved and worn smooth by Gill's hand. It opens the ground in the growing pit's beds so something can be set in it and fed until it grows.",
    type: "tool",
    rarity: "rare",
    icon: "trowel",
    stackable: false,
    maxStackSize: 1,
    equippable: false,
    value: 80,
    weight: 0.3,
  },
  {
    id: "item_sporecraft_wand",
    name: "Sporecraft Wand",
    description:
      "A stem of threaded heartwood grown through with a host's threads and fed on resin until it budded, with a chitin grip. It doesn't press like warding: it bursts, and the spores go where you point. Some of them stay with you, and you breathe the Bloom wherever you carry it.",
    type: "weapon",
    rarity: "rare",
    icon: "fairy-wand",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 300, max: 300 },
    weapon: { style: "magic", damage: 40, speed: 2000 },
    wornEffects: [{ id: "effect_spores", strength: 0.5 }],
    value: 240,
    weight: 1,
  },
  {
    id: "item_thread_balm",
    name: "Thread Balm",
    description:
      "Resin, a white mat and wild honey grown together in the pit's beds into a warm grey paste. Laid on a wound it knits faster than comfrey, and leaves a little of the Bloom in your chest for a while after.",
    type: "consumable",
    rarity: "uncommon",
    icon: "round-potion",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    effects: [
      { id: "effect_rest", strength: 70, duration: 0 },
      { id: "effect_spores", strength: 2, duration: 30 },
    ],
    value: 30,
    weight: 0.3,
  },
  {
    id: "item_heartshell",
    name: "Heartshell",
    description:
      "Shell the Heart grows for itself, dense as bronze and faintly warm, with a grain like wood. A Thresher sheds it in plates. It takes an edge nothing in the Bloom will hold.",
    type: "resource",
    rarity: "rare",
    icon: "armoured-shell",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 80,
    weight: 0.6,
  },
  {
    id: "item_grown_sinew",
    name: "Grown Sinew",
    description:
      "A cord of living threads from a Slinger's throwing arm. Cut free, it still draws itself tight when you pull it, and it never quite stops.",
    type: "resource",
    rarity: "rare",
    icon: "spinal-coil",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 80,
    weight: 0.3,
  },
  {
    id: "item_humming_thread",
    name: "Humming Thread",
    description:
      "A skein of fine grey thread from a Singer's throat. Held to your ear it hums the same note as the Heart, and the note carries through anything it's grown into.",
    type: "resource",
    rarity: "rare",
    icon: "sewing-needle",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 80,
    weight: 0.2,
  },
  {
    id: "item_cracked_wardens_respirator",
    name: "Cracked Warden's Respirator",
    description:
      "A Warden's bronze-and-horn respirator taken off the Heart-Warden, grown through at the seams. Every rivet on the filter is cut with a small closed line, most of them cracked, and a name is scratched inside the cheek-guard: J. WICKEN, KEEPER. Someone who can cut lines could make it hold again.",
    type: "resource",
    rarity: "epic",
    icon: "cracked-mask",
    stackable: false,
    maxStackSize: 1,
    equippable: false,
    value: 400,
    weight: 1.5,
  },
  {
    id: "item_heartshell_blade",
    name: "Heartshell Blade",
    description:
      "A long blade of heartshell ground to an edge along an iron spine, bound at the hilt with grown sinew that tightens in your grip. It opens a Slinger like a pod.",
    type: "weapon",
    rarity: "epic",
    icon: "relic-blade",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 340, max: 340 },
    weapon: { style: "melee", damage: 56, speed: 1800 },
    weight: 2,
    value: 1200,
  },
  {
    id: "item_grown_sinew_bow",
    name: "Grown-Sinew Bow",
    description:
      "Heartshell limbs on a threaded-heartwood riser, strung with grown sinew that draws itself back after every shot. Nothing short of a wall of shell turns what it throws.",
    type: "weapon",
    rarity: "epic",
    icon: "bow-string",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 340, max: 340 },
    weapon: { style: "ranged", damage: 52, speed: 2000 },
    weight: 1.5,
    value: 1200,
  },
  {
    id: "item_humming_staff",
    name: "Humming Staff",
    description:
      "A threaded-heartwood staff grown through with a Singer's thread and capped with heartshell. It hums the Heart's note under your hand and bursts wherever you point it. You breathe the Heart wherever you carry it.",
    type: "weapon",
    rarity: "epic",
    icon: "crescent-staff",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 340, max: 340 },
    weapon: { style: "magic", damage: 50, speed: 2000 },
    wornEffects: [{ id: "effect_spores", strength: 0.5 }],
    weight: 1.5,
    value: 1200,
  },
  {
    id: "item_heartshell_cuirass",
    name: "Heartshell Cuirass",
    description:
      "Heartshell plates on elk hide, with a Warden-steel collar. It sits warm against you like something alive, and turns a Thresher's flail.",
    type: "armor",
    rarity: "epic",
    icon: "chest-armor",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "chest",
    defence: { melee: 96, ranged: 88, magic: 72 },
    value: 1300,
    weight: 6,
  },
  {
    id: "item_heartshell_greaves",
    name: "Heartshell Greaves",
    description:
      "Heartshell plates laced to the knee over elk hide, on an iron frame.",
    type: "armor",
    rarity: "epic",
    icon: "leg-armor",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "legs",
    defence: { melee: 62, ranged: 56, magic: 48 },
    value: 1200,
    weight: 4,
  },
  {
    id: "item_wardens_respirator",
    name: "Warden's Respirator",
    description:
      "The order's own respirator, bronze and horn with a filter of humming thread, its rivets re-cut with closed lines. It's how the Keepers walked in the Heart to cut the first line. It holds off more than any filter ever made at the holdfast, and still not all of it.",
    type: "armor",
    rarity: "epic",
    icon: "trap-mask",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "head",
    defence: { melee: 24, ranged: 20, magic: 40 },
    wornEffects: [{ id: "effect_spore_ward", strength: 240 }],
    value: 1500,
    weight: 1.5,
  },
  {
    id: "item_keystone_focus",
    name: "Keystone Focus",
    description:
      "Ansel Morrow's last work: a chip of the Keystone you re-cut, closed round a thread of the Heart and set in Warden steel. It presses like every warding focus, but it knows the Heart's own shape, and it costs you nothing to carry.",
    type: "weapon",
    rarity: "epic",
    icon: "crystal-growth",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 400, max: 400 },
    weapon: { style: "magic", damage: 56, speed: 2000 },
    value: 1500,
    weight: 1.5,
  },
  {
    id: "item_heartseed_wand",
    name: "Heartseed Wand",
    description:
      "Hollow's gift: a wand grown from a seed of the Threadwell's swell, which opened the day the first line did. It bursts harder than anything grown in the pit, and it breathes the Heart into you wherever you carry it.",
    type: "weapon",
    rarity: "epic",
    icon: "orb-wand",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 400, max: 400 },
    weapon: { style: "magic", damage: 60, speed: 2000 },
    wornEffects: [{ id: "effect_spores", strength: 0.5 }],
    value: 1500,
    weight: 1,
  },
  {
    id: "item_keystone_chip",
    name: "Keystone Chip",
    description:
      "A flake of wardstone lifted off the Keystone when the first line was re-cut clean. It hums against your palm for a moment, then goes quiet.",
    type: "item",
    rarity: "rare",
    icon: "crystal-shine",
    stackable: true,
    maxStackSize: 12,
    equippable: false,
    value: 60,
    weight: 0.2,
  },
  {
    id: "item_unpicked_spur",
    name: "Unpicked Spur",
    description:
      "One of the Keystone's spurs, lifted out of the slab with a dibber and its closed end opened. Nothing hums through it any more.",
    type: "item",
    rarity: "rare",
    icon: "claw",
    stackable: true,
    maxStackSize: 12,
    equippable: false,
    value: 60,
    weight: 0.3,
  },
];

export const itemsById = new Map<string, Item>(
  items.map((item) => [item.id, item]),
);
