import type { Item } from "./types.js";

export const items: Item[] = [
  {
    id: "item_grass_01",
    name: "Wild Grass",
    description:
      "A handful of common wild grass. Can be used in crafting or alchemy.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 1,
    weight: 0.1,
  },
  {
    id: "item_stick_01",
    name: "Wooden Stick",
    description:
      "A common wooden stick found on the ground. Useful for basic crafting and as kindling.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 50,
    equippable: false,
    value: 2,
    weight: 0.5,
  },
  {
    id: "item_log_01",
    name: "Wooden Log",
    description:
      "A sturdy log of wood. Essential for crafting and construction.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    value: 5,
    weight: 2,
  },
  {
    id: "item_stone_01",
    name: "Stone",
    description:
      "A common rock. Useful for crafting tools and building structures.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 50,
    equippable: false,
    value: 1,
    weight: 0.5,
  },
  {
    id: "item_ash_01",
    name: "Ash",
    description: "The remanence of a fire. Useful for gardening.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 50,
    equippable: false,
    value: 1,
    weight: 0.5,
  },
  {
    id: "item_stone_axe_01",
    name: "Stone Axe",
    description: "A simple axe made from a stone head and a wooden handle.",
    type: "item",
    rarity: "common",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 10, max: 10 },
    value: 10,
    weight: 2.5,
    attributes: { damage: 2 },
  },
  {
    id: "item_enchanted_log",
    name: "Enchanted Log",
    description: "A log imbued with magical properties.",
    type: "resource",
    rarity: "rare",
    stackable: true,
    maxStackSize: 10,
    equippable: false,
    value: 50,
    weight: 5,
  },
  {
    id: "item_fairy_petal",
    name: "Fairy Petal",
    description: "A delicate, glowing petal from a fairy flower.",
    type: "resource",
    rarity: "uncommon",
    stackable: true,
    maxStackSize: 50,
    equippable: false,
    value: 20,
    weight: 0.1,
  },
  {
    id: "item_clay",
    name: "Clay",
    description: "Moldable earth, useful for crafting.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 50,
    equippable: false,
    value: 5,
    weight: 1,
  },
  {
    id: "item_cattail_fiber",
    name: "Cattail Fiber",
    description: "Sturdy plant fiber, good for weaving.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 50,
    equippable: false,
    value: 3,
    weight: 0.2,
  },
  {
    id: "item_mountain_rock",
    name: "Mountain Rock",
    description: "A solid rock from high altitudes.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    value: 2,
    weight: 2,
  },
  {
    id: "item_rare_mineral",
    name: "Rare Mineral",
    description: "An uncommon mineral with unique properties.",
    type: "resource",
    rarity: "rare",
    stackable: true,
    maxStackSize: 10,
    equippable: false,
    value: 100,
    weight: 1,
  },
  {
    id: "item_ice_shard",
    name: "Ice Shard",
    description: "A sharp, frozen crystal.",
    type: "resource",
    rarity: "uncommon",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    value: 15,
    weight: 0.5,
  },
  {
    id: "item_frozen_stone",
    name: "Frozen Stone",
    description: "A stone perpetually covered in frost.",
    type: "resource",
    rarity: "uncommon",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    value: 10,
    weight: 1,
  },
  {
    id: "item_ruby",
    name: "Ruby",
    description: "A precious red gemstone.",
    type: "resource",
    rarity: "rare",
    stackable: true,
    maxStackSize: 10,
    equippable: false,
    value: 200,
    weight: 0.1,
  },
  {
    id: "item_glow_fungus",
    name: "Glow Fungus",
    description: "A bioluminescent fungus from dark caves.",
    type: "resource",
    rarity: "uncommon",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    value: 25,
    weight: 0.2,
  },
  {
    id: "item_flower_petals",
    name: "Flower Petals",
    description: "Colorful petals from meadow flowers.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 50,
    equippable: false,
    value: 2,
    weight: 0.1,
  },
  {
    id: "item_wild_grass",
    name: "Wild Grass",
    description: "Fresh grass from sunny meadows.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 50,
    equippable: false,
    value: 1,
    weight: 0.1,
  },
  {
    id: "item_moss_clump",
    name: "Moss Clump",
    description: "A clump of soft, green moss.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 30,
    equippable: false,
    value: 3,
    weight: 0.2,
  },
  {
    id: "item_amethyst",
    name: "Amethyst",
    description: "A beautiful purple crystal.",
    type: "resource",
    rarity: "rare",
    stackable: true,
    maxStackSize: 10,
    equippable: false,
    value: 150,
    weight: 0.1,
  },
  {
    id: "item_crystal_shard",
    name: "Crystal Shard",
    description: "A small, shimmering crystal fragment.",
    type: "resource",
    rarity: "uncommon",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    value: 30,
    weight: 0.1,
  },
  {
    id: "item_iron_ore",
    name: "Iron Ore",
    description: "Raw iron ore, ready for smelting.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    value: 10,
    weight: 2,
  },
  {
    id: "item_dust",
    name: "Dust",
    description: "Fine particles collected from abandoned areas.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 50,
    equippable: false,
    value: 1,
    weight: 0.1,
  },
  {
    id: "item_spring_water",
    name: "Spring Water",
    description: "Pure, refreshing water from a natural spring.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 10,
    equippable: false,
    value: 5,
    weight: 1,
  },
  {
    id: "item_water_plant",
    name: "Water Plant",
    description: "An aquatic plant with various uses.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 30,
    equippable: false,
    value: 4,
    weight: 0.3,
  },
  {
    id: "item_bucket",
    name: "Bucket",
    description: "A simple bucket for carrying liquids or soft materials.",
    type: "tool",
    rarity: "common",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    value: 15,
    weight: 1,
    durability: { current: 100, max: 100 },
  },
  {
    id: "item_spade",
    name: "Spade",
    description: "A basic tool for digging soil and mud.",
    type: "tool",
    rarity: "common",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    value: 20,
    weight: 2,
    durability: { current: 100, max: 100 },
  },
  {
    id: "item_pickaxe",
    name: "Pickaxe",
    description: "A sturdy pickaxe for mining stone and ore.",
    type: "tool",
    rarity: "common",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    value: 30,
    weight: 4,
    durability: { current: 75, max: 75 },
  },
  {
    id: "item_advanced_pickaxe",
    name: "Advanced Pickaxe",
    description: "A high-quality pickaxe for mining tougher materials.",
    type: "tool",
    rarity: "uncommon",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    value: 100,
    weight: 5,
    durability: { current: 150, max: 150 },
  },
  {
    id: "item_ice_pick",
    name: "Ice Pick",
    description: "A specialized tool for breaking and collecting ice.",
    type: "tool",
    rarity: "uncommon",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    value: 50,
    weight: 2,
    durability: { current: 100, max: 100 },
  },
  {
    id: "item_gem_pickaxe",
    name: "Gem Pickaxe",
    description: "A delicate pickaxe designed for extracting precious gems.",
    type: "tool",
    rarity: "rare",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    value: 200,
    weight: 3,
    durability: { current: 100, max: 100 },
  },
  {
    id: "item_gloves",
    name: "Protective Gloves",
    description: "Sturdy gloves to protect hands while gathering resources.",
    type: "tool",
    rarity: "common",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    value: 25,
    weight: 0.5,
    durability: { current: 50, max: 50 },
  },
  {
    id: "item_pruning_shears",
    name: "Pruning Shears",
    description:
      "Sharp shears for cutting branches and collecting plant materials.",
    type: "tool",
    rarity: "common",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    value: 35,
    weight: 1,
    durability: { current: 75, max: 75 },
  },
  {
    id: "item_gem_extractor",
    name: "Gem Extractor",
    description: "A specialized tool for carefully extracting crystal shards.",
    type: "tool",
    rarity: "rare",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    value: 150,
    weight: 2,
    durability: { current: 50, max: 50 },
  },
  {
    id: "item_broom",
    name: "Broom",
    description: "A simple broom for sweeping and collecting dust.",
    type: "tool",
    rarity: "common",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    value: 10,
    weight: 1,
    durability: { current: 100, max: 100 },
  },
  {
    id: "item_water_bottle",
    name: "Water Bottle",
    description: "A bottle for collecting and storing water.",
    type: "tool",
    rarity: "common",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    value: 5,
    weight: 0.5,
    durability: { current: 50, max: 50 },
  },
  {
    id: "item_fishing_net",
    name: "Fishing Net",
    description: "A net for catching fish and collecting water plants.",
    type: "tool",
    rarity: "common",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    value: 40,
    weight: 2,
    durability: { current: 75, max: 75 },
  },
  {
    id: "item_copper_ore",
    name: "Copper Ore",
    description: "A soft, malleable metal ore. Good for basic tools.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    value: 8,
    weight: 1.5,
  },
  {
    id: "item_leather",
    name: "Leather",
    description: "Tanned animal hide, perfect for crafting protective gear.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 30,
    equippable: false,
    value: 15,
    weight: 0.5,
  },
  {
    id: "item_quartz",
    name: "Raw Quartz",
    description: "A common crystal, useful for basic magical implements.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    value: 12,
    weight: 0.3,
  },
  {
    id: "item_vine",
    name: "Strong Vine",
    description: "A sturdy natural rope, useful for binding and crafting.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 40,
    equippable: false,
    value: 5,
    weight: 0.2,
  },
  {
    id: "item_rough_gem",
    name: "Rough Gem",
    description: "An uncut gemstone. Can be found near the surface.",
    type: "resource",
    rarity: "uncommon",
    stackable: true,
    maxStackSize: 15,
    equippable: false,
    value: 25,
    weight: 0.2,
  },
  {
    id: "earthy-moss",
    name: "Earthy Moss",
    description:
      "A soft, green moss that clings to the damp earth of the Verdant Thicket. This common resource is known for its gentle healing properties, making it a favorite among herbalists and apothecaries. Often used in potions and poultices, it symbolizes the enduring resilience of nature.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 100,
    equippable: false,
    value: 5,
    weight: 0.1,
  },
  {
    id: "item_quest_new__yew_tree_s_essence",
    name: "Yew Tree's Essence",
    description:
      "A small vial containing the shimmering essence of the sacred Yew Tree, its luminescent glow pulses gently, resonating with the heartbeat of the forest. This essence is believed to hold the protective magic of the Yew, capable of healing the land and warding off dark forces that threaten its sanctity. The Elunari believe that if harnessed correctly, it can restore the grove's vitality and repel the encroaching darkness from the Mire of Whispers.",
    type: "quest",
    rarity: "rare",
    stackable: false,
    maxStackSize: 1,
    equippable: false,
    value: 150,
    weight: 0.1,
  },
  {
    id: "item_quest_new__veiled_crystaltite_shard",
    name: "Veiled Crystaltite Shard",
    description:
      "A small, translucent shard of Crystaltite, shimmering with an ethereal glow. It pulsates softly with latent magical energy, echoing the life force of the ancient Yew Tree. This shard is a remnant of the Iron Consortium's reckless mining, embodying both the beauty and peril of the land's resources. It can be used to disrupt mining operations or to forge powerful artifacts. Handle with care, for its connection to the grove's magic is profound and delicate.",
    type: "resource",
    rarity: "uncommon",
    stackable: true,
    maxStackSize: 20,
    equippable: false,
    value: 50,
    weight: 0.1,
  },
  {
    id: "item_quest_new__nature_s_embrace_amulet",
    name: "Nature’s Embrace Amulet",
    description:
      "Crafted from the luminous bark of the ancient Yew Tree and embedded with a single Radiant Gem, this amulet pulses with the vibrant energies of the Verdant Thicket. It is said to connect its wearer to the very essence of nature, granting the power to heal wounds and summon the forest's protective spirits in times of need. Legends whisper that in the presence of great danger, the amulet can awaken the Yew Tree's protective magic, shielding its bearer from harm.",
    type: "item",
    rarity: "epic",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "accessory",
    value: 1200,
    weight: 1.5,
  },
  {
    id: "item_quest_new__cursed_essence_fern",
    name: "Cursed Essence Fern",
    description:
      "A rare and eerie plant found only in the Mire of Whispers, the Cursed Essence Fern pulses with a dark energy that thrums in sync with the heartbeat of the forest. Its fronds shimmer with an otherworldly glow, suggesting a connection to the ancient spirits that inhabit Aederyn. This fern is said to possess the power to pacify restless spirits or unleash their wrath, making it an invaluable resource in the quest to confront Sylvara, the awakened protector of the Heartwood Sanctuary.",
    type: "resource",
    rarity: "rare",
    stackable: false,
    maxStackSize: 1,
    equippable: false,
    value: 150,
    weight: 0.2,
  },
  {
    id: "item_quest_new__verdant_embrace_amulet",
    name: "Verdant Embrace Amulet",
    description:
      "Crafted from the sacred boughs of the Heartwood Sanctuary, the Verdant Embrace Amulet pulses with the essence of life itself. Adorned with intricate carvings of flora and fauna, this amulet grants its wearer a deep connection to nature, enhancing their ability to commune with the wild and heal the land. It is said that the spirit Sylvara bestowed this amulet upon those who prove themselves as true guardians of the forest, ensuring that the balance of nature remains undisturbed.",
    type: "item",
    rarity: "epic",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "accessory",
    value: 1500,
    weight: 0.3,
  },
  {
    id: "item_seed_01",
    name: "Wild Seeds",
    description:
      "A pinch of hardy seeds shaken loose from meadow grass. Plant them in tilled soil to grow your own crops.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 2,
    weight: 0.1,
  },
  {
    id: "item_sickle_01",
    name: "Stone Sickle",
    description:
      "A curved stone blade lashed to a wooden handle. Used to harvest crops from your homestead.",
    type: "tool",
    rarity: "common",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 20, max: 20 },
    value: 12,
    weight: 1.5,
  },
  {
    id: "item_fertilizer_01",
    name: "Ash Compost",
    description:
      "A crumbly mix of campfire ash and moss. Restores exhausted soil so it can be planted again.",
    type: "resource",
    rarity: "common",
    stackable: true,
    maxStackSize: 99,
    equippable: false,
    value: 4,
    weight: 0.5,
  },
];

export const itemsById = new Map<string, Item>(
  items.map((item) => [item.id, item]),
);
