import type { Item } from "../../config/types.js";

const material = (id: string, name: string): Item => ({
  id,
  name,
  description: name,
  type: "resource",
  rarity: "common",
  stackable: true,
  maxStackSize: 99,
  equippable: false,
  value: 1,
  weight: 0.1,
});

export const items: Item[] = [
  material("item_grass_01", "Wild Grass"),
  material("item_stick_01", "Wooden Stick"),
  material("item_log_01", "Log"),
  material("item_stone_01", "Stone"),
  material("item_feather", "Feather"),
  {
    id: "item_stone_axe_01",
    name: "Stone Axe",
    description: "An axe.",
    type: "item",
    rarity: "common",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 10, max: 10 },
    value: 10,
    weight: 2.5,
  },
  {
    id: "item_wooden_club",
    name: "Wooden Club",
    description: "A club.",
    type: "weapon",
    rarity: "common",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "mainHand",
    durability: { current: 60, max: 60 },
    weapon: { style: "melee", damage: 10, speed: 2000 },
    value: 12,
    weight: 2.5,
  },
  {
    id: "item_torch",
    name: "Torch",
    description: "A torch.",
    type: "item",
    rarity: "common",
    stackable: false,
    maxStackSize: 1,
    equippable: true,
    equipSlot: "offHand",
    wornEffects: [{ id: "effect_light", strength: 1 }],
    value: 5,
    weight: 1,
  },
  {
    id: "item_forager_brew",
    name: "Forager's Brew",
    description: "A brew.",
    type: "consumable",
    rarity: "common",
    stackable: true,
    maxStackSize: 10,
    equippable: false,
    effects: [{ id: "effect_bountiful", strength: 50, duration: 120 }],
    value: 5,
    weight: 0.2,
  },
  {
    id: "item_herb_poultice",
    name: "Herb Poultice",
    description: "A poultice.",
    type: "consumable",
    rarity: "common",
    stackable: true,
    maxStackSize: 10,
    equippable: false,
    effects: [{ id: "effect_rest", strength: 20, duration: 0 }],
    value: 5,
    weight: 0.2,
  },
];

export const itemsById = new Map<string, Item>(items.map((item) => [item.id, item]));
